name: Generate Logo
on:
  workflow_dispatch:
    inputs:
      description:
        description: 'What does your project do?'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  models: read  # Required for GitHub's AI models

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate logo with AI
        uses: jmcpheron/chiaro-oscuro@main
        with:
          project-name: ${{ github.event.repository.name }}
          description: ${{ inputs.description }}
          github-token: ${{ secrets.GITHUB_TOKEN }}